// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwzjqaucuxfwswmoyjuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3empxYXVjdXhmd3N3bW95anVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjEyOTUsImV4cCI6MjA2NTg5NzI5NX0.FQc1VGLa9ytErcOl_QF87HHfPEXe2TIgmAtO-Ou7beM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);